# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d102679659e4515be9bcddfc230736329eb402c379e4389c8e8106ebe568e6663c6c150dba6185cd729c911b90f289d96750563b9ee87e0dfe5a2a8e4964a4b3

test:
  secret_key_base: 550137f7ee242c2e89859e42204696159debe9bde91e9cd27db4de1bd4ea0a2933ed7c1b36d6d93986fc01991afc55ed6b395c5f43ae568657ae535032f094b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
